"""aaa

Revision ID: 0af3f4505a3c
Revises: 0b9b17d48b3a
Create Date: 2023-07-09 23:08:02.306036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0af3f4505a3c'
down_revision = '0b9b17d48b3a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
