"""aaa

Revision ID: 0b9b17d48b3a
Revises: 2c4a9bafdb7b
Create Date: 2023-07-08 19:43:38.780730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b9b17d48b3a'
down_revision = '2c4a9bafdb7b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplies', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplies', 'status')
    # ### end Alembic commands ###
