"""aaa

Revision ID: 2c4a9bafdb7b
Revises: 03c4bf94f301
Create Date: 2023-07-08 19:39:33.877494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c4a9bafdb7b'
down_revision = '03c4bf94f301'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=999), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('amount_type', sa.String(length=999), nullable=True),
    sa.Column('category', sa.String(length=999), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplies')
    # ### end Alembic commands ###
