"""aaa

Revision ID: 3e84fe49f635
Revises: 0af3f4505a3c
Create Date: 2023-07-10 01:37:02.902645

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3e84fe49f635'
down_revision = '0af3f4505a3c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incomes', 'comment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incomes', sa.Column('comment', mysql.VARCHAR(length=999), nullable=True))
    # ### end Alembic commands ###
