"""aaa

Revision ID: 7fdf6f9f0cbb
Revises: 8b565da3ac53
Create Date: 2023-07-10 01:43:29.654355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fdf6f9f0cbb'
down_revision = '8b565da3ac53'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
