"""aaa

Revision ID: 894f8a157097
Revises: fa3d668b0385
Create Date: 2023-07-03 02:16:01.964044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '894f8a157097'
down_revision = 'fa3d668b0385'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token', sa.String(length=999), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token')
    # ### end Alembic commands ###
