"""aaa

Revision ID: 8b565da3ac53
Revises: 3e84fe49f635
Create Date: 2023-07-10 01:42:56.511275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b565da3ac53'
down_revision = '3e84fe49f635'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('price', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'price')
    # ### end Alembic commands ###
