"""aaa

Revision ID: a1e1ab471bed
Revises: 7fdf6f9f0cbb
Create Date: 2023-07-10 02:08:33.200403

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a1e1ab471bed'
down_revision = '7fdf6f9f0cbb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('supply_id', sa.Integer(), nullable=True))
    op.drop_column('expenses', 'product_id')
    op.drop_column('expenses', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('amount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('expenses', sa.Column('product_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('expenses', 'supply_id')
    # ### end Alembic commands ###
