"""aaa

Revision ID: fa3d668b0385
Revises: 6ae069a19709
Create Date: 2023-07-03 01:33:00.039737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa3d668b0385'
down_revision = '6ae069a19709'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=999), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('customers', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.add_column('expenses', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.add_column('incomes', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.add_column('trades', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('branch_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'branch_id')
    op.drop_column('trades', 'branch_id')
    op.drop_column('products', 'branch_id')
    op.drop_column('orders', 'branch_id')
    op.drop_column('incomes', 'branch_id')
    op.drop_column('expenses', 'branch_id')
    op.drop_column('customers', 'branch_id')
    op.drop_table('branches')
    # ### end Alembic commands ###
